apiVersion: v1
kind: ConfigMap
metadata:
  name: backend
  namespace: expense
data:
  DB_HOST: "mysql"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: expense
  # these are replica set labels
  labels:
    project: expense
    component: backend
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      project: expense
      component: backend
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        project: expense
        component: backend
        tier: backend
    spec:
      containers:
      - name: backend
        image: "{{ .Values.deployment.imageRepo }}:{{ .Values.deployment.imageVersion}}"
        imagePullPolicy: IfNotPresent
        envFrom:
        - configMapRef:
            name: backend
        ports:
        - name: liveness-port
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
        livenessProbe:
          httpGet:
            path: /health
            port: liveness-port
          failureThreshold: 1
          periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: expense
spec:
  selector:
    project: expense
    component: backend
    tier: backend
  ports:
    - protocol: TCP
      port: {{ .Values.service.servicePort }} # service port
      targetPort: 8080 # container port